import Main from "@/components/layouts/Main";
import MoreInfoSection from "@/components/MoreInfoSection/MoreInfoSection";
import SideBar from "@/components/SideBar/SideBar";
import SummarySection from "@/components/SummarySection/SummarySection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main className="flex">
        <SideBar />
        <SummarySection />
        <MoreInfoSection />
      </Main>
    </>
  );
}
